package jdbc;

import object.User;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;

/**
 * Class UserJDBC
 */
public class UserDAO {
    private Connection connectDataBase;

    /**
     * Constructor UserJDBC
     *
     * @param connectDataBase Creates a Statement object for sending SQL statements to the database.
     */
    public UserDAO(Connection connectDataBase) {
        this.connectDataBase = connectDataBase;
    }


    /**
     * Insert object User to database USER
     *
     * @param user Object of the User
     */
    public void addUser(User user) {
        PreparedStatement prepStatement;

        try {
            prepStatement = connectDataBase.prepareStatement("INSERT INTO \"public\".\"USER\" VALUES (?, ?, ?, ?, ?, ?, ?)");
            prepStatement = setQueryUser(user, prepStatement);
            prepStatement.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * Set SQL Query from user object
     *
     * @param userHandler Object of the User
     * @return Modified Prepared Statement
     */
    private PreparedStatement setQueryUser(User userHandler, PreparedStatement preparedStatementHandler) throws SQLException {
            preparedStatementHandler.setInt(1, userHandler.id);
            preparedStatementHandler.setString(2, userHandler.name);
            preparedStatementHandler.setObject(3, userHandler.birthday);
            preparedStatementHandler.setInt(4, userHandler.login_id);
            preparedStatementHandler.setString(5, userHandler.city);
            preparedStatementHandler.setString(6, userHandler.email);
            preparedStatementHandler.setString(7, userHandler.description);

        return preparedStatementHandler;
    }

    /**
     * Get object User from database USER
     *
     * @return Query from user
     */
    public User readUser(Integer idUser) {
        PreparedStatement prepStatement;
        User queryUser = null;
        try {
            prepStatement = connectDataBase.prepareStatement("SELECT * FROM \"public\".\"USER\" WHERE (id = ?)");

            prepStatement.setInt(1, idUser);

            ResultSet resultSet = prepStatement.executeQuery();
            if (resultSet.next()) {
                queryUser = fromResultSet(resultSet);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return queryUser;
    }

    /**
     * Get object User from set
     *
     * @param resultSet A table of data representing a database result set, which
     *                  is usually generated by executing a statement that queries the database.
     * @return Object User
     * @throws SQLException An exception that provides information on a database access error or other errors.
     */
    private static User fromResultSet(ResultSet resultSet) throws SQLException {
        return new User(resultSet.getInt("id"), resultSet.getString("name"),
                resultSet.getObject("birthday", LocalDate.class), resultSet.getInt("login_id"),
                resultSet.getString("city"), resultSet.getString("email"),
                resultSet.getString("description"));
    }

    /**
     * Update object User from database USER
     *
     * @param user Object of the User
     */
    public void updateUser(User user) {
        PreparedStatement prepStatement;
        try {
            prepStatement = connectDataBase.prepareStatement("UPDATE \"public\".\"USER\" SET id = ?, name = ?, birthday = ?, login_id = ?,city = ?, email = ?, description = ? WHERE id = ?");
            setQueryUser(user, prepStatement);
            prepStatement.setInt(8, user.id);
            prepStatement.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * Delete object User from database USER
     *
     * @param user Object User
     */
    public void deleteUser(User user) {

        PreparedStatement prepStatement;
        try {
            prepStatement = connectDataBase.prepareStatement("DELETE FROM \"public\".\"USER\" WHERE id = ?");
            prepStatement.setInt(1, user.id);
            prepStatement.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}
