package jdbc;

import object.UserRole;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 * Class UserRoleJDBC
 */
public class UserRoleDAO {
    private Connection connectDataBase;

    /**
     * Constructor RoleDJDBC
     *
     * @param connectDataBase Creates a Statement object for sending SQL statements to the database.
     */
    public UserRoleDAO(Connection connectDataBase) {
        this.connectDataBase = connectDataBase;
    }

    /**
     * Insert object UserRole to database USER_ROLE
     *
     * @param userRole Object of the UserRole
     */
    public void addUserRole(UserRole userRole) {
        try (PreparedStatement prepStatement = connectDataBase.prepareStatement("INSERT INTO \"public\".\"USER_ROLE\" VALUES (?, ?, ?)")) {
            prepStatement.setInt(1, userRole.id);
            prepStatement.setInt(2, userRole.user_id);
            prepStatement.setInt(3, userRole.role_id);
            prepStatement.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * Read object UserRole from database USER_ROLE
     *
     * @return Query from userRole
     */
    public UserRole readUserRole(Integer queryToRead) {
        PreparedStatement prepStatement;
        UserRole queryUserRole = null;
        try {
            prepStatement = connectDataBase.prepareStatement("SELECT * FROM \"public\".\"USER_ROLE\" WHERE (id = ?)");
            prepStatement.setInt(1, queryToRead);
            try (ResultSet resultSet = prepStatement.executeQuery()) {
                if (resultSet.next()) {
                    queryUserRole = fromResultSet(resultSet);
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return queryUserRole;
    }

    /**
     * Get object UserRole from set
     *
     * @param resultSet A table of data representing a database result set, which
     *                  is usually generated by executing a statement that queries the database.
     * @return Object UserRole
     * @throws SQLException An exception that provides information on a database access error or other errors.
     */
    private static UserRole fromResultSet(ResultSet resultSet) throws SQLException {
        return new UserRole(resultSet.getInt("id"),
                resultSet.getInt("user_id"),
                resultSet.getInt("role_id"));
    }

    /**
     * Update object UserRole from database USER
     *
     * @param userRole Object of the UserRole
     */
    public void updateUser(UserRole userRole) {
        PreparedStatement prepStatement;
        try {
            prepStatement = connectDataBase.prepareStatement("UPDATE \"public\".\"USER_ROLE\" SET id = ?, user_id = ?, role_id = ? WHERE id = ?");
            prepStatement.setInt(1, userRole.id);
            prepStatement.setInt(2, userRole.user_id);
            prepStatement.setInt(3, userRole.role_id);
            prepStatement.setInt(4, userRole.id);
            prepStatement.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * Delete object UserRole from database USER_ROLE
     *
     * @param userRole Object User_Role
     */
    public void deleteUserRole(UserRole userRole) {
        PreparedStatement prepStatement;
        
        try {
            prepStatement = connectDataBase.prepareStatement("DELETE FROM \"public\".\"USER_ROLE\" WHERE id = ?");
            prepStatement.setInt(1, userRole.id);
            prepStatement.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}